# COURSE: A deep understanding of deep learning
## SECTION: Math prerequisites
### LECTURE: Matrix multiplication
#### TEACHER: Mike X Cohen, sincxpress.com
##### COURSE URL: udemy.com/course/deeplearning_x/?couponCode=202401

In [1]:
# import libraries
import numpy as np
import torch

# Using numpy

In [2]:
# create some random matrices
A = np.random.randn(3,4)
B = np.random.randn(4,5)
C = np.random.randn(3,7)

# try some multiplications...
print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@C   ,2)), print(' ')
# print(np.round( B@C   ,2)), print(' ')
print(np.round( C.T@A ,2))

[[-1.49  2.31  1.85  0.93  0.48]
 [-2.31  2.9   5.1   2.04 -1.83]
 [ 1.23  2.84 -2.5  -0.25  1.18]]
 
[[-1.4   0.48 -3.11  1.06]
 [ 0.05  2.68 -0.29  0.87]
 [-0.47 -2.65 -0.32 -0.57]
 [-0.74  2.56 -2.02  1.33]
 [ 0.13 -0.65  0.78 -0.27]
 [ 0.69  2.77 -4.32  0.02]
 [ 0.69  2.21  1.25  0.31]]


# Using pytorch

In [3]:
# create some random matrices
A  = torch.randn(3,4)
B  = torch.randn(4,5)
C1 = np.random.randn(4,7)
C2 = torch.tensor( C1,dtype=torch.float )

# try some multiplications...
# print(np.round( A@B   ,2)), print(' ')
# print(np.round( A@B.T ,2)), print(' ')
print(np.round( A@C1  ,2)), print(' ')
print(np.round( A@C2  ,2))

tensor([[ 1.9000,  1.2000,  1.5100, -0.3800, -3.3300, -0.1300, -0.2700],
        [-0.2400,  0.4900, -0.0800,  1.8700,  0.1100, -0.8200, -0.9500],
        [ 1.5100,  0.3600,  0.9200, -0.0300, -0.8300,  0.2900, -0.6000]],
       dtype=torch.float64)
 
tensor([[ 1.9000,  1.2000,  1.5100, -0.3800, -3.3300, -0.1300, -0.2700],
        [-0.2400,  0.4900, -0.0800,  1.8700,  0.1100, -0.8200, -0.9500],
        [ 1.5100,  0.3600,  0.9200, -0.0300, -0.8300,  0.2900, -0.6000]])
